//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEcom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string Client_name { get; set; }
        public string Client_adress { get; set; }
        public string Client_Email { get; set; }
        public int Client_Id { get; set; }
        public string Client_json { get; set; }
    }
}
