//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEcom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Product = new HashSet<Product>();
            this.MessageTB = new HashSet<MessageTB>();
        }

        public int User_Id { get; set; }
        [Display(Name = "Insert login")]
        public string User_login { get; set; }
        
        [Display(Name = "Insert Password")]
        [DataType(DataType.Password)]
        public string User_password { get; set; }
        
        [Display(Name = "Insert your email")]
        public string User_Email { get; set; }
       
        [Display(Name = "Insert again password")]
        [Compare("User_password",ErrorMessage ="Try please again.")]
        [DataType(DataType.Password)]
        public string User_password_1 { get; set; }
        public byte[] ImageDATA { get; set; }
        public string ImageMMType { get; set; }
        public string User_message { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageTB> MessageTB { get; set; }
    }
}
